module.exports = {
  client: {
    JOIN_GAME: "JOIN_GAME",
    QUIT_GAME: "QUIT_GAME",
    CLICKED_CARD: "CLICKED_CARD",
    FORM_SUBMISSION: "FORM_SUBMISSION",
    READY: "READY",
  },
  server: {
    BEGIN_COUNTDOWN: "BEGIN_COUNTDOWN",
    FLIP_CARD: "FLIP_CARD",
    SHOW_FORM: "SHOW_FORM",
    SHOW_ANNOUNCEMENT: "SHOW_ANNOUNCEMENT",
    BEGIN_ROUND: "BEGIN_ROUND",

    BROADCAST: {
      DATA_SYNC: "DATA_SYNC",
      NEW_MEMBER: "NEW_MEMBER",
    },
  },
};
