module.exports = {
  COUNTDOWN: "COUNTDOWN",
  CARD_REACTION_TIME: "CARD_REACTION_TIME",
  PENDING_FORM_RESPONSES: "PENDING_FORM_RESPONSES",
  PENDING_READY_RESPONSES: "PENDING_READY_RESPONSES",
  PENDING_CARD_CLICK: "PENDING_CARD_CLICK",
};
